# Generated by Django 5.2.12 on 2026-03-21 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='reward_first_try',
            field=models.PositiveIntegerField(default=10),
        ),
        migrations.AddField(
            model_name='quiz',
            name='reward_fourth_plus',
            field=models.PositiveIntegerField(default=2),
        ),
        migrations.AddField(
            model_name='quiz',
            name='reward_second_try',
            field=models.PositiveIntegerField(default=8),
        ),
        migrations.AddField(
            model_name='quiz',
            name='reward_third_try',
            field=models.PositiveIntegerField(default=5),
        ),
        migrations.AddField(
            model_name='quizattempt',
            name='attempt_number',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='quizattempt',
            name='points_earned',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
