# Generated by Django 5.2.12 on 2026-03-21 13:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assets', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContentEntity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entity_type', models.PositiveSmallIntegerField(choices=[(1, 'Course'), (2, 'Module'), (3, 'Lesson'), (4, 'Video'), (5, 'Quiz'), (6, 'Article'), (7, 'Resource')])),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, max_length=280, unique=True)),
                ('short_description', models.CharField(blank=True, max_length=500)),
                ('description', models.TextField(blank=True)),
                ('status_code', models.PositiveSmallIntegerField(choices=[(1, 'Draft'), (2, 'Published'), (3, 'Archived'), (4, 'Hidden')], default=1)),
                ('estimated_duration_seconds', models.PositiveIntegerField(blank=True, null=True)),
                ('allow_standalone_enrollment', models.BooleanField(default=False)),
                ('is_reusable', models.BooleanField(default=False)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('archived_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_entities', to=settings.AUTH_USER_MODEL)),
                ('thumbnail_asset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='assets.asset')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ArticleContent',
            fields=[
                ('entity', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='article_detail', serialize=False, to='content.contententity')),
                ('body_markdown', models.TextField(blank=True)),
                ('reading_time_seconds', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='EntityStats',
            fields=[
                ('entity', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='stats', serialize=False, to='content.contententity')),
                ('direct_child_count', models.PositiveIntegerField(default=0)),
                ('required_child_count', models.PositiveIntegerField(default=0)),
                ('total_duration_seconds', models.PositiveIntegerField(default=0)),
                ('enrollment_count', models.PositiveIntegerField(default=0)),
                ('completion_count', models.PositiveIntegerField(default=0)),
                ('average_rating', models.DecimalField(decimal_places=2, default=0, max_digits=3)),
                ('total_reviews', models.PositiveIntegerField(default=0)),
                ('total_points_awarded', models.PositiveIntegerField(default=0)),
                ('views_count', models.PositiveIntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='LessonContent',
            fields=[
                ('entity', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='lesson_detail', serialize=False, to='content.contententity')),
                ('lesson_format', models.PositiveSmallIntegerField(choices=[(1, 'Text'), (2, 'Mixed'), (3, 'Guided'), (4, 'Wrapper')], default=1)),
                ('body', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='QuizContent',
            fields=[
                ('entity', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='quiz_detail', serialize=False, to='content.contententity')),
                ('instructions', models.TextField(blank=True)),
                ('attempt_limit', models.PositiveIntegerField(default=0)),
                ('pass_percentage', models.PositiveIntegerField(default=50)),
                ('shuffle_questions', models.BooleanField(default=False)),
                ('shuffle_options', models.BooleanField(default=False)),
                ('show_answers_after_submit', models.BooleanField(default=True)),
                ('show_score_immediately', models.BooleanField(default=True)),
                ('time_limit_seconds', models.PositiveIntegerField(blank=True, null=True)),
                ('allow_resume', models.BooleanField(default=False)),
                ('award_points', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='CompletionRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rule_type', models.PositiveSmallIntegerField(choices=[(1, 'All required children'), (2, 'Any N children'), (3, 'Pass quiz'), (4, 'Watch percentage'), (5, 'Manual mark complete')])),
                ('rule_config', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='completion_rules', to='content.contententity')),
            ],
        ),
        migrations.CreateModel(
            name='ContentAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('external_url', models.URLField(blank=True, max_length=500)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('asset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='assets.asset')),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='content.contententity')),
            ],
            options={
                'ordering': ['sort_order'],
            },
        ),
        migrations.CreateModel(
            name='ContentStructure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('is_required', models.BooleanField(default=True)),
                ('is_preview', models.BooleanField(default=False)),
                ('unlock_rule_code', models.PositiveSmallIntegerField(choices=[(1, 'Immediate'), (2, 'After previous'), (3, 'After prerequisite'), (4, 'Scheduled'), (5, 'Manual')], default=1)),
                ('unlock_rule_config', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('child_entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parent_links', to='content.contententity')),
                ('parent_entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='children_links', to='content.contententity')),
            ],
            options={
                'ordering': ['sort_order'],
            },
        ),
        migrations.CreateModel(
            name='EntityPrerequisite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prerequisites', to='content.contententity')),
                ('required_entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dependents', to='content.contententity')),
            ],
        ),
        migrations.CreateModel(
            name='CourseSettings',
            fields=[
                ('entity', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='course_settings', serialize=False, to='content.contententity')),
                ('visibility_code', models.PositiveSmallIntegerField(choices=[(1, 'Everyone'), (2, 'Signed In')], default=1)),
                ('access_rule_code', models.PositiveSmallIntegerField(choices=[(1, 'Open'), (2, 'On Invitation'), (3, 'On Payment')], default=1)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('website', models.URLField(blank=True, max_length=500)),
                ('level_code', models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Beginner'), (2, 'Intermediate'), (3, 'Advanced')], null=True)),
                ('responsible', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='responsible_courses', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ResourceContent',
            fields=[
                ('entity', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='resource_detail', serialize=False, to='content.contententity')),
                ('resource_url', models.URLField(blank=True, max_length=500)),
                ('resource_kind', models.PositiveSmallIntegerField(choices=[(1, 'PDF'), (2, 'Image'), (3, 'Worksheet'), (4, 'Attachment'), (5, 'External link')], default=4)),
                ('allow_download', models.BooleanField(default=False)),
                ('asset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='assets.asset')),
            ],
        ),
        migrations.CreateModel(
            name='VideoContent',
            fields=[
                ('entity', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='video_detail', serialize=False, to='content.contententity')),
                ('video_url', models.URLField(blank=True, max_length=500)),
                ('streaming_provider', models.PositiveSmallIntegerField(choices=[(1, 'Direct S3'), (2, 'CloudFront'), (3, 'HLS / Streaming')], default=1)),
                ('duration_seconds', models.PositiveIntegerField(default=0)),
                ('transcript_text', models.TextField(blank=True)),
                ('allow_download', models.BooleanField(default=False)),
                ('autoplay_enabled', models.BooleanField(default=False)),
                ('captions_asset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='assets.asset')),
                ('poster_asset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='assets.asset')),
                ('video_asset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='assets.asset')),
            ],
        ),
        migrations.AddIndex(
            model_name='contententity',
            index=models.Index(fields=['entity_type', 'status_code'], name='content_con_entity__e9e672_idx'),
        ),
        migrations.AddIndex(
            model_name='contententity',
            index=models.Index(fields=['owner', 'entity_type'], name='content_con_owner_i_a07d17_idx'),
        ),
        migrations.AddIndex(
            model_name='contentstructure',
            index=models.Index(fields=['parent_entity', 'sort_order'], name='content_con_parent__166861_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='contentstructure',
            unique_together={('parent_entity', 'child_entity')},
        ),
        migrations.AlterUniqueTogether(
            name='entityprerequisite',
            unique_together={('entity', 'required_entity')},
        ),
    ]
