# Generated by Django 5.2.12 on 2026-03-21 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_course_tags_course_website_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='category',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
