from django.urls import path

from .manager_views import (
    ContentTreeView,
    EntityAttachmentDeleteView,
    EntityChildRemoveView,
    EntityChildrenView,
    EntityCreateView,
    EntityDetailView,
    EntityUploadView,
    ReorderChildrenView,
    StandaloneEntitiesView,
)
from .views import (
    AdminCategoryListView,
    AdminCourseListView,
    AdminLessonListView,
    AdminModuleListView,
    AttachmentDetailView,
    CategoryDetailView,
    CategoryListCreateView,
    CourseDetailView,
    CourseLessonListCreateView,
    CourseListCreateView,
    CoursePublishView,
    LessonAttachmentListCreateView,
    LessonCompleteView,
    LessonDetailView,
    LessonListCreateView,
    LessonQuizListCreateView,
    ModuleDetailView,
    ModuleListCreateView,
    ModuleQuizListCreateView,
    PlatformStatsView,
)

urlpatterns = [
    # ── Content Manager (unified API) ──
    path('cm/tree/', ContentTreeView.as_view(), name='cm-tree'),
    path('cm/entities/', EntityCreateView.as_view(), name='cm-entity-create'),
    path('cm/entities/standalone/', StandaloneEntitiesView.as_view(), name='cm-standalone'),
    path('cm/entities/<int:pk>/', EntityDetailView.as_view(), name='cm-entity-detail'),
    path('cm/entities/<int:pk>/children/', EntityChildrenView.as_view(), name='cm-entity-children'),
    path('cm/entities/<int:pk>/children/<int:child_id>/', EntityChildRemoveView.as_view(), name='cm-entity-child-remove'),
    path('cm/entities/<int:pk>/upload/', EntityUploadView.as_view(), name='cm-entity-upload'),
    path('cm/entities/<int:pk>/reorder/', ReorderChildrenView.as_view(), name='cm-entity-reorder'),
    path('cm/attachments/<int:pk>/', EntityAttachmentDeleteView.as_view(), name='cm-attachment-delete'),
    # ── Legacy endpoints (kept for compatibility) ──
    path('categories/', CategoryListCreateView.as_view(), name='category-list-create'),
    path('categories/<int:pk>/', CategoryDetailView.as_view(), name='category-detail'),
    path('courses/', CourseListCreateView.as_view(), name='course-list-create'),
    path('courses/<int:pk>/', CourseDetailView.as_view(), name='course-detail'),
    path('courses/<int:pk>/publish/', CoursePublishView.as_view(), name='course-publish'),
    path('courses/<int:course_id>/modules/', ModuleListCreateView.as_view(), name='module-list-create'),
    path('courses/<int:course_id>/lessons/', CourseLessonListCreateView.as_view(), name='course-lesson-list-create'),
    path('modules/<int:pk>/', ModuleDetailView.as_view(), name='module-detail'),
    path('modules/<int:module_id>/lessons/', LessonListCreateView.as_view(), name='lesson-list-create'),
    path('modules/<int:module_id>/quizzes/', ModuleQuizListCreateView.as_view(), name='module-quiz-list-create'),
    path('lessons/<int:pk>/', LessonDetailView.as_view(), name='lesson-detail'),
    path('lessons/<int:pk>/complete/', LessonCompleteView.as_view(), name='lesson-complete'),
    path('lessons/<int:lesson_id>/attachments/', LessonAttachmentListCreateView.as_view(), name='lesson-attachment-list-create'),
    path('lessons/<int:lesson_id>/quizzes/', LessonQuizListCreateView.as_view(), name='lesson-quiz-list-create'),
    path('attachments/<int:pk>/', AttachmentDetailView.as_view(), name='attachment-detail'),
    path('admin/categories/', AdminCategoryListView.as_view(), name='admin-categories'),
    path('admin/courses/', AdminCourseListView.as_view(), name='admin-courses'),
    path('admin/modules/', AdminModuleListView.as_view(), name='admin-modules'),
    path('admin/lessons/', AdminLessonListView.as_view(), name='admin-lessons'),
    path('stats/', PlatformStatsView.as_view(), name='platform-stats'),
]
