# Generated by Django 5.2.12 on 2026-03-21 13:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('content', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invited_email', models.EmailField(blank=True, max_length=254)),
                ('invite_token', models.CharField(blank=True, max_length=64, null=True, unique=True)),
                ('membership_status', models.PositiveSmallIntegerField(choices=[(1, 'Invited'), (2, 'Active'), (3, 'Completed'), (4, 'Revoked'), (5, 'Expired')], default=2)),
                ('access_mode', models.PositiveSmallIntegerField(choices=[(1, 'Open'), (2, 'Invitation'), (3, 'Admin assigned'), (4, 'Imported')], default=1)),
                ('invited_at', models.DateTimeField(blank=True, null=True)),
                ('enrolled_at', models.DateTimeField(blank=True, null=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('last_accessed_at', models.DateTimeField(blank=True, null=True)),
                ('progress_percent', models.PositiveSmallIntegerField(default=0)),
                ('time_spent_seconds', models.PositiveIntegerField(default=0)),
                ('course_entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='content.contententity')),
                ('invited_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invitations_sent', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='course_memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['course_entity', 'membership_status'], name='enrollment__course__5fb44d_idx'), models.Index(fields=['user', 'membership_status'], name='enrollment__user_id_66a658_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('user__isnull', False)), fields=('course_entity', 'user'), name='unique_course_user_membership')],
            },
        ),
        migrations.CreateModel(
            name='EntityProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('progress_status', models.PositiveSmallIntegerField(choices=[(1, 'Not started'), (2, 'In progress'), (3, 'Completed'), (4, 'Failed'), (5, 'Locked')], default=1)),
                ('progress_percent', models.PositiveSmallIntegerField(default=0)),
                ('last_position_seconds', models.PositiveIntegerField(blank=True, null=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('last_accessed_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress_records', to='content.contententity')),
                ('learner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entity_progress', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('learner', 'entity')},
            },
        ),
    ]
